### ISSUE TITLE
Barcode should probably not be int?

### ISSUE THREAD

**Issue by ryanavella** [bhutch29/abv#14]
On a 32-bit architecture, an int can represent any number up to +2147483647. However, a lot of common barcode standards require 10 or more digits. So a totally valid barcode such as 9876543210 would overflow our model's barcode field.

How should we remedy this? We could use int64, which can support up to 18 decimal digits. Or uint64 which supports up to 19 digits. Or maybe should we go for something more robust like a string?

**Comment by bhutch29** [comment]
You are totally right! I thing string makes the most sense. Ill make that change now, but note that you will need to delete your local .sqlite database to prevent weird duplicate tables (pretty much need to delete it after every change to the model anyway, so nothing new here)
