### ISSUE TITLE
Fetching consumption for each week -- is this valid?

### ISSUE THREAD

**Issue by ryanavella** [bhutch29/abv#27]
I think it'd be useful to be able to query the sqlite database and see the consumption for each week. I'm not very familiar with SQL syntax and grammar however. Here is my attempt to accomplish it. Is this valid?

```
package model

import "fmt"

type Date int64

type DateRange struct {
	Start Date
	End   Date
}

// GetOutputWithinDateRange returns every drink served within a date range, inclusive
func (m *Model) GetOutputWithinDateRange(dates DateRange) (result []StockedDrink, err error) {
	sql := `
select A.*,
  case
    when C.OutputQuantity is null then 0
    else C.OutputQuantity
  end as quantity
from Drinks as A

left join (
  select barcode, sum(quantity) as OutputQuantity
  from Output as O where O.Date >= %v and O.Date <= %v
  group by barcode
) as C
on A.Barcode = C.Barcode

where quantity > 0
order by A.Brand
`
	err = m.db.Select(&result, fmt.Sprintf(sql, dates.Start, dates.End))
	return result, err
}

```

**Comment by bhutch29** [comment]
Nothing obvious wrong with it. Have to run it and see what happens!
One small formatting thing, SQLX package supports variables using '?'s, so you should be able to replace `err = m.db.Select(&result, fmt.Sprintf(sql, dates.Start, dates.End))` with `err = m.db.Select(&result, sql, dates.Start, dates.End)` if you replace the %v with ?

**Comment by ryanavella** [comment]
I did some quick tests and it seemed to work fine. Just wasn't sure if this code might break for some weird edge cases. I'll do a pull request for now, if we find problems later we can always patch it.

**Comment by bhutch29** [comment]
Sounds good. Don't think it will be connected right away anyway, have to find something that will utilize it. Good to have though!
