### ISSUE TITLE
Support for brewery nicknames in database

### ISSUE THREAD

**Issue by ryanavella** [bhutch29/abv#32]
To help keep the inventory view compact, it would be nice to have support for brewery nicknames.

For example:
- Deschutes Brewery --> Deschutes
- Lagunitas Brewing Company --> Lagunitas
- Blue Moon Brewing Company --> Blue Moon

We could add this to the model as an optional field. This makes me think that we might want a separate sql table for associating brewery names with nicknames.

I think it is best if it is entered manually, either in some sort of "administration mode," or in a dedicated sqlite viewer. If left default/blank, the formatter defaults to the full brewery name.

If we don't like modifying the model and database, another option is to implement a nickname guesser. This guesser could strip certain common suffixes from the end of a string, like "brewery" or "brewing company." I personally don't like this solution however because it could break for unusual brewery names.

**Comment by bhutch29** [comment]
I think this is a great idea. Lets go with a new table called BreweryNicknames, two columns:
1. Barcode (primary key)
2. BreweryNickname

Then we can join by nickname and use it if it exists, otherwise use full name, all in sql

**Comment by bhutch29** [comment]
Barely started it, see feature/nicknames branch

**Comment by bhutch29** [comment]
whoops
