### ISSUE TITLE
Look for sqlite table and nickname csv in $HOME / %HOMEPATH% (OS independent)

### ISSUE THREAD

**Issue by ryanavella** [bhutch29/abv#43]
For example, $HOME/abv (Unix-like) or %HOMEPATH$\abv (Windows)

**Comment by bhutch29** [comment]
https://github.com/mitchellh/go-homedir

**Comment by ryanavella** [comment]
I'm wondering how go-homedir differs from a solution like this. Am I overlooking some sort of edge case that go-homedir handles better?

```golang
import (
	"os"
	"os/user"
	"path/filepath"
)
user, err := user.Current()
if err != nil {
	// handle error
}
file, err := os.Open(filepath.Join(user.HomeDir, "abv", "filename.txt"))
if err != nil {
	// handle error
}
```

**Comment by bhutch29** [comment]
My brief online search said that os/user depends on cgo and so can cause some cross platform issues. But if it works for you on windows and it works on Linux, then its good enough for our purposes!

**Comment by ryanavella** [comment]
Whoops, I shoulda read the readme of go-homedir. If go-homedir works for Windows and Raspberry Pi, let's go with that.

**Comment by bhutch29** [comment]
Used the external config file handling to manage this
