### ISSUE TITLE
Support for beer name nicknames

### ISSUE THREAD

**Issue by bhutch29** [bhutch29/abv#45]

**Comment by bhutch29** [comment]
I just found the package [viper](https://github.com/spf13/viper) and will be using it for reading configuration information from files. It supports TOML and YAML syntax, which support maps. We may want to consider moving nickname stuff into the same config file...

**Comment by ryanavella** [comment]
I'm all for it, that would at least tidy up our current mess of user-supplied files, databases, and environment variables.
