### ISSUE TITLE
Ability to serve drinks by name rather than barcode

### ISSUE THREAD

**Issue by ryanavella** [bhutch29/abv#59]
This is totally nontrivial and would require at least two heuristics:
- Differentiating barcodes from drink names
- Finding the closest match to a drink in inventory, from the given name

The first could be accomplished by looking at the alphanumeric distribution as well as the number of space-delimited "words." The second probably requires the support of a third-party library.

Would be helpful for those especially tricky barcodes that refuse to scan (goddammit Modelo)

**Comment by ryanavella** [comment]
This may be unnecessary with a higher-end barcode scanner. Will determine soon.

**Comment by bhutch29** [comment]
Gotta be honest. Flagging this as out of scope and closing it. Solution: buy a nice barcode scanner
