### ISSUE TITLE
Updates to config file have to happen in two places (config file and cleanup script)

### ISSUE THREAD

**Issue by bhutch29** [bhutch29/abv#73]
Is it possible to remove the config template from the python script so i dont have to change things in two places?

**Comment by ryanavella** [comment]
I can see two ways to solve this:
1. A new template file, in addition to config.toml and the cleanup script (easy)
2. A modified toml parser that preserves comments and insertion order (more difficult)

I'm leaning towards option 2. It will take a little longer to come up with, but will be more robust and applicable to other projects I might work on in the future.
